### ISSUE TITLE
Lots of <Error> ServerErrorHandler: Code: 101, e.displayText() = DB::NetException: Unexpected packet from client, e.what() = DB::NetException

### ISSUE THREAD

**Issue by djeshkov** [yandex/ClickHouse#1534]
We are getting this errors on the only 'Distributed' table we have. It's being sharded across 3 servers.

clickhouse-server.err.log:

2017.11.22 08:07:33.892000 [ 351 ] <Error> ServerErrorHandler: Code: 99, e.displayText() = DB::Exception: Unknown packet from client, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x330dbc6]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x146c8ff]
2. clickhouse-server(DB::TCPHandler::receivePacket()+0x1f3) [0x1479373]
3. clickhouse-server(DB::TCPHandler::runImpl()+0x508) [0x147a9e8]
4. clickhouse-server(DB::TCPHandler::run()+0x1c) [0x147b71c]
5. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x39ab75f]
6. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xad) [0x39c9b5d]
7. clickhouse-server(Poco::PooledThread::run()+0x86) [0x38ed396]
8. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x38c0aa8]
9. clickhouse-server() [0x40f595f]
10. /lib/x86_64-linux-gnu/libpthread.so.0(+0x7494) [0x7fe2e0fd8494]
11. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fe2e060aaff]

Clickhouse server versions - 1.1.54310

Could anyone explain what does this error mean and provide any solution on how we could solve this.

Thanks

**Comment by msoltyspl** [comment]
This looks quite similar to what I'm getting (#1522) - from common parts between our cases, we both use distributed tables (in my case 3 shards x 2 replicas). ('Code' is different though 99 vs 101).

**Comment by blinkov** [comment]
@djeshkov was everything else working fine besides this messages in log?

**Comment by doom369** [comment]
@blinkov getting the same error, few hundreds of records in 1 batch once per minute:

```
2019.08.14 16:31:16.739119 [ 43 ] {} <Error> ServerErrorHandler: Code: 101, e.displayText() = DB::NetException: Unexpected packet from client, Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x30) [0x7f58f30]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x25) [0x3c427b5]
2. /usr/bin/clickhouse-server() [0x37b9d98]
3. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x1f4) [0x3c83704]
4. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x3c847cb]
5. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0x10) [0x792cde0]
6. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xed) [0x792d4fd]
7. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x8057e21]
8. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x3c) [0x8055bcc]
9. /usr/bin/clickhouse-server() [0xba2baa0]
10. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f33f58bb6db]
11. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f33f504288f]
 (version 19.13.1.11 (official build))
```

Happens with java jdbc client when performing batch updates. On the server side periodically I see dropped connections due to timeout. Timing is very close so probably this is related.

```
Caused by: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 159, host: 10.132.135.133, port: 8123; Read timed out
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:82) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:24) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:628) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:114) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:97) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:92) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:87) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:223) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:164) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:185) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
        at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
        at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:609) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:114) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:97) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:92) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:87) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:223) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:164) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:185) ~[airiusfans-0.56.1-SNAPSHOT.jar:?]

```
