### ISSUE TITLE
Crash on SHOW TABLES request

### ISSUE THREAD

**Issue by fsitedev** [yandex/ClickHouse#1617]
Version: 54318

Got exception on simple SHOW TABLES request:
```bash
# clickhouse-client
ClickHouse client version 1.1.54318.
Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.54318.

:) show tables
SHOW TABLES

Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000, 127.0.0.1

Connecting to localhost:9000.
Code: 210. DB::NetException: Connection refused: (localhost:9000, 127.0.0.1)
```

Clickhouse logs:
```bash
2017.12.11 14:10:45.123938 [ 6 ] <Error> BaseDaemon: ########################################
2017.12.11 14:10:45.123977 [ 6 ] <Error> BaseDaemon: (from thread 5) Received signal Illegal instruction (4).
2017.12.11 14:10:45.180711 [ 6 ] <Error> BaseDaemon: 0. clickhouse-server() [0x2ebc7c8]
2017.12.11 14:10:45.180782 [ 6 ] <Error> BaseDaemon: 1. clickhouse-server(DB::ITableDeclaration::check(std::vector<std::string, std::allocator<std::string> > const&) const+0x47) [0x2ebdc27]
2017.12.11 14:10:45.180819 [ 6 ] <Error> BaseDaemon: 2. clickhouse-server(DB::StorageSystemTables::read(std::vector<std::string, std::allocator<std::string> > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum&, unsigned long, unsigned int)+0x2f) [0x2784c5f]
2017.12.11 14:10:45.180843 [ 6 ] <Error> BaseDaemon: 3. clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns()+0xe81) [0x2d8bab1]
2017.12.11 14:10:45.180874 [ 6 ] <Error> BaseDaemon: 4. clickhouse-server(DB::InterpreterSelectQuery::executeSingleQuery()+0x23) [0x2d88303]
2017.12.11 14:10:45.180895 [ 6 ] <Error> BaseDaemon: 5. clickhouse-server(DB::InterpreterSelectQuery::executeWithoutUnion()+0x16d) [0x2d8a4bd]
2017.12.11 14:10:45.180916 [ 6 ] <Error> BaseDaemon: 6. clickhouse-server(DB::InterpreterSelectQuery::execute()+0x22) [0x2d8a502]
2017.12.11 14:10:45.180936 [ 6 ] <Error> BaseDaemon: 7. clickhouse-server() [0x2e10e89]
2017.12.11 14:10:45.180960 [ 6 ] <Error> BaseDaemon: 8. clickhouse-server(DB::executeQuery(std::string const&, DB::Context&, bool, DB::QueryProcessingStage::Enum)+0x126) [0x2e12706]
2017.12.11 14:10:45.180982 [ 6 ] <Error> BaseDaemon: 9. clickhouse-server(DB::InterpreterShowTablesQuery::execute()+0x35) [0x3211855]
2017.12.11 14:10:45.181000 [ 6 ] <Error> BaseDaemon: 10. clickhouse-server() [0x2e10e89]
2017.12.11 14:10:45.181023 [ 6 ] <Error> BaseDaemon: 11. clickhouse-server(DB::executeQuery(std::string const&, DB::Context&, bool, DB::QueryProcessingStage::Enum)+0x126) [0x2e12706]
2017.12.11 14:10:45.181046 [ 6 ] <Error> BaseDaemon: 12. clickhouse-server(DB::TCPHandler::runImpl()+0x591) [0x13c7ff1]
2017.12.11 14:10:45.181066 [ 6 ] <Error> BaseDaemon: 13. clickhouse-server(DB::TCPHandler::run()+0x1c) [0x13c8c0c]
2017.12.11 14:10:45.181088 [ 6 ] <Error> BaseDaemon: 14. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x33ba3bf]
2017.12.11 14:10:45.181125 [ 6 ] <Error> BaseDaemon: 15. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x112) [0x33baa32]
2017.12.11 14:10:45.181146 [ 6 ] <Error> BaseDaemon: 16. clickhouse-server(Poco::PooledThread::run()+0x86) [0x3322ba6]
2017.12.11 14:10:45.181166 [ 6 ] <Error> BaseDaemon: 17. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x331f498]
2017.12.11 14:10:45.181185 [ 6 ] <Error> BaseDaemon: 18. clickhouse-server() [0x36aba4f]
2017.12.11 14:10:45.181203 [ 6 ] <Error> BaseDaemon: 19. /lib64/libpthread.so.0(+0x7aa1) [0x7f033c3c8aa1]
```

Zookeeper logs:
```bash
2017-12-11 14:10:39,768 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /127.0.0.1:60602
2017-12-11 14:10:39,769 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@807] - Connection request from old client /127.0.0.1:60602; will be dropped if server is in r-o mode
2017-12-11 14:10:39,769 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@853] - Client attempting to establish new session at /127.0.0.1:60602
2017-12-11 14:10:39,800 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@609] - Established session 0x1604542c5750001 with negotiated timeout 30000 for client /127.0.0.1:60602
2017-12-11 14:10:39,802 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67b0 zxid:0x18 txntype:-1 reqpath:n/a Error Path:/clickhouse Error:KeeperErrorCode = NodeExists for /clickhouse
2017-12-11 14:10:39,816 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67b1 zxid:0x19 txntype:-1 reqpath:n/a Error Path:/clickhouse/task_queue Error:KeeperErrorCode = NodeExists for /clickhouse/task_queue
2017-12-11 14:10:39,825 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67b2 zxid:0x1a txntype:-1 reqpath:n/a Error Path:/clickhouse/task_queue/resharding Error:KeeperErrorCode = NodeExists for /clickhouse/task_queue/resharding
2017-12-11 14:10:39,840 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67b3 zxid:0x1b txntype:-1 reqpath:n/a Error Path:/clickhouse/task_queue/resharding/mediator-1411.mediator.ptstage1.devmail.ru Error:KeeperErrorCode = NodeExists for /clickhouse/task_queue/resharding/mediator-1411.mediator.ptstage1.devmail.ru
2017-12-11 14:10:39,866 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67b4 zxid:0x1c txntype:-1 reqpath:n/a Error Path:/clickhouse Error:KeeperErrorCode = NodeExists for /clickhouse
2017-12-11 14:10:39,874 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67b5 zxid:0x1d txntype:-1 reqpath:n/a Error Path:/clickhouse/task_queue Error:KeeperErrorCode = NodeExists for /clickhouse/task_queue
2017-12-11 14:10:39,878 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67b6 zxid:0x1e txntype:-1 reqpath:n/a Error Path:/clickhouse/task_queue/resharding_distributed Error:KeeperErrorCode = NodeExists for /clickhouse/task_queue/resharding_distributed
2017-12-11 14:10:39,883 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67b7 zxid:0x1f txntype:-1 reqpath:n/a Error Path:/clickhouse/task_queue/resharding_distributed/online Error:KeeperErrorCode = NodeExists for /clickhouse/task_queue/resharding_distributed/online
2017-12-11 14:10:39,910 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67b9 zxid:0x21 txntype:-1 reqpath:n/a Error Path:/clickhouse/task_queue/resharding_distributed/lock Error:KeeperErrorCode = NodeExists for /clickhouse/task_queue/resharding_distributed/lock
2017-12-11 14:10:39,934 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67ba zxid:0x22 txntype:-1 reqpath:n/a Error Path:/clickhouse Error:KeeperErrorCode = NodeExists for /clickhouse
2017-12-11 14:10:39,952 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67bb zxid:0x23 txntype:-1 reqpath:n/a Error Path:/clickhouse/task_queue Error:KeeperErrorCode = NodeExists for /clickhouse/task_queue
2017-12-11 14:10:39,961 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67bc zxid:0x24 txntype:-1 reqpath:n/a Error Path:/clickhouse/task_queue/resharding_distributed Error:KeeperErrorCode = NodeExists for /clickhouse/task_queue/resharding_distributed
2017-12-11 14:10:40,044 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67bd zxid:0x25 txntype:-1 reqpath:n/a Error Path:/clickhouse/task_queue/resharding_distributed/coordination Error:KeeperErrorCode = NodeExists for /clickhouse/task_queue/resharding_distributed/coordination
2017-12-11 14:10:40,072 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67be zxid:0x26 txntype:-1 reqpath:n/a Error Path:/clickhouse Error:KeeperErrorCode = NodeExists for /clickhouse
2017-12-11 14:10:40,081 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67c1 zxid:0x27 txntype:-1 reqpath:n/a Error Path:/clickhouse/task_queue Error:KeeperErrorCode = NodeExists for /clickhouse/task_queue
2017-12-11 14:10:40,096 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1604542c5750001 type:create cxid:0x5a2e67c2 zxid:0x28 txntype:-1 reqpath:n/a Error Path:/clickhouse/task_queue/ddl Error:KeeperErrorCode = NodeExists for /clickhouse/task_queue/ddl
2017-12-11 14:10:55,128 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@360] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x1604542c5750001, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:231)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
	at java.lang.Thread.run(Thread.java:748)
2017-12-11 14:10:55,132 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1037] - Closed socket connection for client /127.0.0.1:60602 which had sessionid 0x1604542c5750001
2017-12-11 14:11:22,001 [myid:] - INFO  [SessionTracker:ZooKeeperServer@325] - Expiring session 0x1604542c5750001, timeout of 30000ms exceeded
2017-12-11 14:11:22,002 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@494] - Processed session termination for sessionid: 0x1604542c5750001
```

**Comment by blinkov** [comment]
@fsitedev you definitely had some other circumstances that have lead to this, what are they?
Can you reproduce this on recent ClickHouse releases?

**Comment by fsitedev** [comment]
Yes, we have already solved this issue. The old version of SSE was the reason. Thank you!
