### ISSUE TITLE
ReplicatedMergeTree Engine Checksum mismatch for uncompressed file error

### ISSUE THREAD

**Issue by tacyuuhon** [yandex/ClickHouse#1659]
Hi

My server side runs the ClickHouse version of 1.1.54318
Client writes 1K rows of data in each batch, write 1K times per minute
When I write data to ReplicatedMergeTree, the server side will have the following error log.

> Server log
```
clickhouse-server    | 2017.12.18 08:43:12.206098 [ 19 ] <Debug> default.server_log_replic (Merger): Merge sorted 64592 rows, containing 13 columns (13 merged, 0 gathered) in 0.04 sec., 1472411.34 rows/sec., 223.20 MB/sec.
clickhouse-server    | 2017.12.18 08:43:12.211039 [ 19 ] <Error> default.server_log_replic (StorageReplicatedMergeTree): Code: 40, e.displayText() = DB::Exception: Checksum mismatch for uncompressed file d_7.bin in data part, e.what() = DB::Exception. Data after merge is not byte-identical to data on another replicas. There could be several reasons: 1. Using newer version of compression library after server update. 2. Using another compression method. 3. Non-deterministic compression algorithm (highly unlikely). 4. Non-deterministic merge algorithm due to logical error in code. 5. Data corruption in memory due to bug in code. 6. Data corruption in memory due to hardware issue. 7. Manual modification of source data after server startup. 8. Manual modification of checksums stored in ZooKeeper. We will download merged part from replica to force byte-identical result.
clickhouse-server    | 2017.12.18 08:43:12.211070 [ 19 ] <Debug> MemoryTracker: Peak memory usage: 142.39 MiB.
clickhouse-server    | 2017.12.18 08:43:12.212904 [ 19 ] <Debug> default.server_log_replic (StorageReplicatedMergeTree): Fetching part 20171215_20171218_42_47_1 from /clickhouse/tables/server_log/replicas/CLICK0004
clickhouse-server    | 2017.12.18 08:43:12.213272 [ 19 ] <Trace> ReadWriteBufferFromHTTP: Sending request to http://CLICK0004:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fserver_log%2Freplicas%2FCLICK0004&part=20171215_20171218_42_47_1&shard=&compress=false
clickhouse-server    | 2017.12.18 08:43:12.244063 [ 19 ] <Error> DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 40, e.displayText() = DB::Exception: Checksum mismatch for uncompressed file d_7.bin in data part, e.what() = DB::Exception, Stack trace:
clickhouse-server    | 
clickhouse-server    | 0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x3221296]
clickhouse-server    | 1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x144a02f]
clickhouse-server    | 2. /usr/bin/clickhouse-server(DB::MergeTreeDataPartChecksum::checkEqual(DB::MergeTreeDataPartChecksum const&, bool, std::string const&) const+0xca) [0x33b1f2a]
clickhouse-server    | 3. /usr/bin/clickhouse-server(DB::MergeTreeDataPartChecksums::checkEqual(DB::MergeTreeDataPartChecksums const&, bool) const+0x94) [0x33b2504]
clickhouse-server    | 4. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::checkPartAndAddToZooKeeper(std::shared_ptr<DB::MergeTreeDataPart const> const&, std::vector<std::unique_ptr<zkutil::Op, std::default_delete<zkutil::Op> >, std::allocator<std::unique_ptr<zkutil::Op, std::default_delete<zkutil::Op> > > >&, std::string)+0x86c) [0x332059c]
clickhouse-server    | 5. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::fetchPart(std::string const&, std::string const&, bool, unsigned long)+0x480) [0x3333ab0]
clickhouse-server    | 6. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry const&)+0x1269) [0x3335b39]
clickhouse-server    | 7. /usr/bin/clickhouse-server() [0x3338580]
clickhouse-server    | 8. /usr/bin/clickhouse-server(DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>)+0x3e) [0x3420fbe]
clickhouse-server    | 9. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::queueTask()+0x163) [0x3322853]
clickhouse-server    | 10. /usr/bin/clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x436) [0x3375646]
clickhouse-server    | 11. /usr/bin/clickhouse-server() [0x40983df]
clickhouse-server    | 12. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7ff7388036ba]
clickhouse-server    | 13. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ff737e243dd]
clickhouse-server    | 
clickhouse-server    | 2017.12.18 08:43:12.324970 [ 23 ] <Trace> default.server_log_replic (StorageReplicatedMergeTree): Executing log entry to merge parts 20171215_20171218_97_97_0, 20171215_20171218_98_98_0, 20171215_20171218_99_99_0, 20171215_20171218_100_100_0, 20171215_20171218_101_101_0, 20171215_20171218_102_102_0 to 20171215_20171218_97_102_1
clickhouse-server    | 2017.12.18 08:43:12.325004 [ 23 ] <Debug> default.server_log_replic (Merger): Merging 6 parts: from 20171215_20171218_97_97_0 to 20171215_20171218_102_102_0 into tmp_merge_20171215_20171218_97_102_1
clickhouse-server    | 2017.12.18 08:43:12.325409 [ 23 ] <Debug> default.server_log_replic (Merger): Selected MergeAlgorithm: Horizontal
clickhouse-server    | 2017.12.18 08:43:12.325428 [ 23 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20171215_20171218_97_97_0, approx. 16384 rows starting from 0
clickhouse-server    | 2017.12.18 08:43:12.325502 [ 23 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20171215_20171218_98_98_0, approx. 16384 rows starting from 0
clickhouse-server    | 2017.12.18 08:43:12.325525 [ 23 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20171215_20171218_99_99_0, approx. 16384 rows starting from 0
clickhouse-server    | 2017.12.18 08:43:12.325533 [ 23 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20171215_20171218_100_100_0, approx. 16384 rows starting from 0
clickhouse-server    | 2017.12.18 08:43:12.325541 [ 23 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20171215_20171218_101_101_0, approx. 16384 rows starting from 0
clickhouse-server    | 2017.12.18 08:43:12.325549 [ 23 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20171215_20171218_102_102_0, approx. 16384 rows starting from 0
clickhouse-server    | 2017.12.18 08:43:12.370299 [ 23 ] <Debug> default.server_log_replic (Merger): Merge sorted 66498 rows, containing 13 columns (13 merged, 0 gathered) in 0.05 sec., 1468521.33 rows/sec., 221.27 MB/sec.
clickhouse-server    | 2017.12.18 08:43:12.373970 [ 23 ] <Error> default.server_log_replic (StorageReplicatedMergeTree): Code: 40, e.displayText() = DB::Exception: Checksum mismatch for uncompressed file d_7.bin in data part, e.what() = DB::Exception. Data after merge is not byte-identical to data on another replicas. There could be several reasons: 1. Using newer version of compression library after server update. 2. Using another compression method. 3. Non-deterministic compression algorithm (highly unlikely). 4. Non-deterministic merge algorithm due to logical error in code. 5. Data corruption in memory due to bug in code. 6. Data corruption in memory due to hardware issue. 7. Manual modification of source data after server startup. 8. Manual modification of checksums stored in ZooKeeper. We will download merged part from replica to force byte-identical result.
clickhouse-server    | 2017.12.18 08:43:12.374002 [ 23 ] <Debug> MemoryTracker: Peak memory usage: 142.65 MiB.
clickhouse-server    | 2017.12.18 08:43:12.376654 [ 23 ] <Debug> default.server_log_replic (StorageReplicatedMergeTree): Fetching part 20171215_20171218_97_102_1 from /clickhouse/tables/server_log/replicas/CLICK0004
clickhouse-server    | 2017.12.18 08:43:12.377002 [ 23 ] <Trace> ReadWriteBufferFromHTTP: Sending request to http://CLICK0004:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fserver_log%2Freplicas%2FCLICK0004&part=20171215_20171218_97_102_1&shard=&compress=false
clickhouse-server    | 2017.12.18 08:43:12.402628 [ 25 ] <Trace> default.server_log_replic (StorageReplicatedMergeTree): Executing log entry to merge parts 20171215_20171218_73_73_0, 20171215_20171218_74_74_0, 20171215_20171218_75_75_0, 20171215_20171218_76_76_0, 20171215_20171218_77_77_0, 20171215_20171218_78_78_0 to 20171215_20171218_73_78_1
clickhouse-server    | 2017.12.18 08:43:12.402659 [ 25 ] <Debug> default.server_log_replic (Merger): Merging 6 parts: from 20171215_20171218_73_73_0 to 20171215_20171218_78_78_0 into tmp_merge_20171215_20171218_73_78_1
clickhouse-server    | 2017.12.18 08:43:12.403087 [ 25 ] <Debug> default.server_log_replic (Merger): Selected MergeAlgorithm: Horizontal
clickhouse-server    | 2017.12.18 08:43:12.403107 [ 25 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20171215_20171218_73_73_0, approx. 16384 rows starting from 0
clickhouse-server    | 2017.12.18 08:43:12.403142 [ 25 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20171215_20171218_74_74_0, approx. 16384 rows starting from 0
clickhouse-server    | 2017.12.18 08:43:12.403152 [ 25 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20171215_20171218_75_75_0, approx. 16384 rows starting from 0
clickhouse-server    | 2017.12.18 08:43:12.403175 [ 25 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20171215_20171218_76_76_0, approx. 16384 rows starting from 0
clickhouse-server    | 2017.12.18 08:43:12.403183 [ 25 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20171215_20171218_77_77_0, approx. 16384 rows starting from 0
clickhouse-server    | 2017.12.18 08:43:12.403190 [ 25 ] <Trace> MergeTreeBlockInputStream: Reading 1 ranges from part 20171215_20171218_78_78_0, approx. 16384 rows starting from 0
clickhouse-server    | 2017.12.18 08:43:12.414568 [ 23 ] <Error> DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 40, e.displayText() = DB::Exception: Checksum mismatch for uncompressed file d_7.bin in data part, e.what() = DB::Exception, Stack trace:
clickhouse-server    | 
clickhouse-server    | 0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x3221296]
clickhouse-server    | 1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x144a02f]
clickhouse-server    | 2. /usr/bin/clickhouse-server(DB::MergeTreeDataPartChecksum::checkEqual(DB::MergeTreeDataPartChecksum const&, bool, std::string const&) const+0xca) [0x33b1f2a]
clickhouse-server    | 3. /usr/bin/clickhouse-server(DB::MergeTreeDataPartChecksums::checkEqual(DB::MergeTreeDataPartChecksums const&, bool) const+0x94) [0x33b2504]
clickhouse-server    | 4. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::checkPartAndAddToZooKeeper(std::shared_ptr<DB::MergeTreeDataPart const> const&, std::vector<std::unique_ptr<zkutil::Op, std::default_delete<zkutil::Op> >, std::allocator<std::unique_ptr<zkutil::Op, std::default_delete<zkutil::Op> > > >&, std::string)+0x86c) [0x332059c]
clickhouse-server    | 5. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::fetchPart(std::string const&, std::string const&, bool, unsigned long)+0x480) [0x3333ab0]
clickhouse-server    | 6. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry const&)+0x1269) [0x3335b39]
clickhouse-server    | 7. /usr/bin/clickhouse-server() [0x3338580]
clickhouse-server    | 8. /usr/bin/clickhouse-server(DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>)+0x3e) [0x3420fbe]
clickhouse-server    | 9. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::queueTask()+0x163) [0x3322853]
clickhouse-server    | 10. /usr/bin/clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x436) [0x3375646]
clickhouse-server    | 11. /usr/bin/clickhouse-server() [0x40983df]
clickhouse-server    | 12. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7ff7388036ba]
clickhouse-server    | 13. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ff737e243dd]
```
> Client log
```
2017-12-18 08:42:39.826 ERROR 2739 --- [ntainer#0-0-L-1] clickhouse.ServerLogListener     : ClickHouse exception, code: 252, host: 10.115.112.165, port: 8123; ;�Wpε^x����j����kCode: 252, e.displayText() = DB::Exception: Too many parts (358). Merges are processing significantly slower than inserts.q;whajPtion


ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 252, host: 192.168.1.4, port: 8123; ;�Wpε^x����j����kCode: 252, e.displayText() = DB::Exception: Too many parts (358). Merges are processing significantly slower than inserts.q;whajPtion

        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:58) ~[clickhouse-jdbc-0.1.34.jar!/:na]
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28) ~[clickhouse-jdbc-0.1.34.jar!/:na]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:664) ~[clickhouse-jdbc-0.1.34.jar!/:na]
        at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:640) ~[clickhouse-jdbc-0.1.34.jar!/:na]
        at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:363) ~[clickhouse-jdbc-0.1.34.jar!/:na]
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_141]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
Caused by: java.lang.Throwable: ;�Wpε^x����j����kCode: 252, e.displayText() = DB::Exception: Too many parts (358). Merges are processing significantly slower than inserts.q;whajPtion

        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53) ~[clickhouse-jdbc-0.1.34.jar!/:na]
        ... 22 common frames omitted
```

My config file is as follows:
> config.xml
```
<remote_servers>
		<server_logs>
			<shard>
				<internal_replication>true</internal_replication>
				<replica>
					<host>CLICK0001</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>CLICK0003</host>
					<port>9000</port>
				</replica>
			</shard>
			
			<shard>
				<internal_replication>true</internal_replication>
				<replica>
					<host>CLICK0002</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>CLICK0005</host>
					<port>9000</port>
				</replica>
			</shard>

			<shard>
				<internal_replication>true</internal_replication>
				<replica>
					<host>CLICK0003</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>CLICK0002</host>
					<port>9000</port>
				</replica>
			</shard>

			<shard>
				<internal_replication>true</internal_replication>
				<replica>
					<host>CLICK0004</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>CLICK0001</host>
					<port>9000</port>
				</replica>
			</shard>

			<shard>
				<internal_replication>true</internal_replication>
				<replica>
					<host>CLICK0005</host>
					<port>9000</port>
				</replica>
				<replica>
					<host>CLICK0004</host>
					<port>9000</port>
				</replica>
			</shard>
		</server_logs>
</remote_servers>

<zookeeper>
  <node index="1">
        <host>192.168.1.1</host>
        <port>2181</port>
    </node>
      <node index="2">
        <host>192.168.1.2</host>
        <port>2181</port>
    </node>
    <node index="3">
        <host>192.168.1.3</host>
        <port>2181</port>
    </node>
      <node index="4">
        <host>192.168.1.4</host>
        <port>2181</port>
    </node>
      <node index="5">
        <host>192.168.1.5</host>
        <port>2181</port>
    </node>
</zookeeper>
```

> table schema
```
CREATE TABLE default.server_log_replic (
  d_1 Date,
  d_2 DateTime,
  d_3 UInt64,
  d_4 String,
  d_5 String,
  d_6 String,
  d_7 String,
  d_8 String,
  d_9 String,
  d_10 UInt32,
  d_11 UInt32,
  d_12 UInt32,
  d_13 UInt32
) ENGINE = ReplicatedMergeTree(
  '/clickhouse/tables/server_log',
  '{host}',
  d_1,
  rand(),
  (d_1, d_2, rand()),
  8192
)
```

**Comment by silviucpp** [comment]
I've run in the same issues with two machines that were not on the same os (one osx and one ubuntu)

**Comment by tacyuuhon** [comment]
Maybe I've made it wrong.
I think it's going to work like the Kafka replication mode.
So, I corrected the wrong config. Let it work again.

> config.xml
```
<remote_servers>
  <server_logs>

    <shard>
      <internal_replication>true</internal_replication>
      <replica>
        <host>CLICK0001</host>
        <port>9000</port>
      </replica>
      <replica>
        <host>CLICK0002</host>
        <port>9000</port>
      </replica>
    </shard>
    
    <shard>
      <internal_replication>true</internal_replication>
      <replica>
        <host>CLICK0003</host>
        <port>9000</port>
      </replica>
      <replica>
        <host>CLICK0004</host>
        <port>9000</port>
      </replica>
    </shard>

    <shard>
      <!--  <internal_replication>true</internal_replication> -->
      <replica>
        <host>CLICK0005</host>
        <port>9000</port>
      </replica>
    </shard>

  </server_logs>
</remote_servers>
```

> table schema
```
(CLICK0001, CLICK0002):
--------------------------
CREATE TABLE default.server_log_replic (
  ...
) ENGINE = ReplicatedMergeTree(
  '/clickhouse/tables/1/server_log',
  '{host}',
  d_1,
  rand(),
  (d_1, d_2, rand()),
  8192
)


(CLICK0003, CLICK0004):
--------------------------
CREATE TABLE default.server_log_replic (
  ...
) ENGINE = ReplicatedMergeTree(
  '/clickhouse/tables/2/server_log',
  '{host}',
  d_1,
  rand(),
  (d_1, d_2, rand()),
  8192
)


(CLICK0005):
------------
CREATE TABLE default.server_log_replic (
  ...
) ENGINE = ReplicatedMergeTree(
  '/clickhouse/tables/3/server_log',
  '{host}',
  d_1,
  rand(),
  (d_1, d_2, rand()),
  8192
)
```

That is to say, if I have 6 host, I can only have three shards. Is it right for me to understand this?
Work like Kafka replication mode.How should config it?

**Comment by blinkov** [comment]
@tacyuuhon have you finally fixed these issues on your own?

**Comment by tacyuuhon** [comment]
@blinkov 
Yes, it looks like I just made a wrong config.
