### ISSUE TITLE
KafkaEngine hides startup error

### ISSUE THREAD

**Issue by tobad357** [yandex/ClickHouse#2075]
If there is a table using KafkaEngine defined and Clickhouse has an issue starting up related to invalid table sql definitions for another table and/or possibly other startup errors the KafkaEngine will get stuck and the underlying issue will not show in logs.

If the Kafka engine sql file is removed from metadata/ then the server will startup and print the underlying issue.

One way of testing this is to add a union statement to an existing materialized view

See gdb output from when the sever is stuck

```
[New LWP 13]
[New LWP 14]
[New LWP 15]
[New LWP 16]
[New LWP 17]
[New LWP 18]
[New LWP 19]
[New LWP 20]
[New LWP 21]
[New LWP 22]
[New LWP 23]
[New LWP 24]
[New LWP 25]
[New LWP 26]
[New LWP 27]
[New LWP 28]
[New LWP 29]
[New LWP 30]
[New LWP 31]
[New LWP 32]
[New LWP 33]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185	../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.

Thread 22 (Thread 0x7f02f282b700 (LWP 33)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f282b700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 21 (Thread 0x7f02f302c700 (LWP 32)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f302c700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 20 (Thread 0x7f02f382d700 (LWP 31)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f382d700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 19 (Thread 0x7f02f402e700 (LWP 30)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f402e700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 18 (Thread 0x7f02f482f700 (LWP 29)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f482f700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 17 (Thread 0x7f02f5030700 (LWP 28)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f5030700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 16 (Thread 0x7f02f5831700 (LWP 27)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f5831700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 15 (Thread 0x7f02f6032700 (LWP 26)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f6032700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 14 (Thread 0x7f02f6833700 (LWP 25)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f6833700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 13 (Thread 0x7f02f7034700 (LWP 24)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f7034700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 12 (Thread 0x7f02f7835700 (LWP 23)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f7835700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 11 (Thread 0x7f02f8036700 (LWP 22)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f8036700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 10 (Thread 0x7f02f8837700 (LWP 21)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f8837700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 9 (Thread 0x7f02f9038700 (LWP 20)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f9038700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 8 (Thread 0x7f02f9839700 (LWP 19)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02f9839700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7f02fa03a700 (LWP 18)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000007e312f9 in DB::BackgroundProcessingPool::threadFunction() ()
#2  0x0000000008d6705f in ?? ()
#3  0x00007f02fdb7c6ba in start_thread (arg=0x7f02fa03a700) at pthread_create.c:333
#4  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7f02fa83b700 (LWP 17)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000083c788b in do_completion ()
#2  0x00007f02fdb7c6ba in start_thread (arg=0x7f02fa83b700) at pthread_create.c:333
#3  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7f02fb03c700 (LWP 16)):
#0  0x00007f02fd59d74d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000000083c770d in do_io ()
#2  0x00007f02fdb7c6ba in start_thread (arg=0x7f02fb03c700) at pthread_create.c:333
#3  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7f02fbc5f700 (LWP 15)):
#0  0x00007f02fdb8551d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000000082c8fb8 in DB::ReadBufferFromFileDescriptor::nextImpl() ()
#2  0x0000000005e6e80a in SignalListener::run() ()
#3  0x0000000008bae798 in Poco::ThreadImpl::runnableEntry(void*) ()
#4  0x0000000008d6705f in ?? ()
#5  0x00007f02fdb7c6ba in start_thread (arg=0x7f02fbc5f700) at pthread_create.c:333
#6  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7f02fc460700 (LWP 14)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000008d2773c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#2  0x0000000008b2f24b in Poco::Event::wait() ()
#3  0x0000000008bb25eb in Poco::PooledThread::run() ()
#4  0x0000000008bae798 in Poco::ThreadImpl::runnableEntry(void*) ()
#5  0x0000000008d6705f in ?? ()
#6  0x00007f02fdb7c6ba in start_thread (arg=0x7f02fc460700) at pthread_create.c:333
#7  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f02fcc61700 (LWP 13)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000008d2773c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#2  0x0000000008b2f24b in Poco::Event::wait() ()
#3  0x0000000008bb25eb in Poco::PooledThread::run() ()
#4  0x0000000008bae798 in Poco::ThreadImpl::runnableEntry(void*) ()
#5  0x0000000008d6705f in ?? ()
#6  0x00007f02fdb7c6ba in start_thread (arg=0x7f02fcc61700) at pthread_create.c:333
#7  0x00007f02fd5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f02fe3b9800 (LWP 12)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000008d2773c in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#2  0x0000000008b9d593 in Poco::Semaphore::wait() ()
#3  0x00000000081626cc in DB::StorageKafka::shutdown() ()
#4  0x00000000080127dd in DB::DatabaseOrdinary::shutdown() ()
#5  0x0000000007c7f90d in DB::ContextShared::shutdown() ()
#6  0x0000000007c82fa8 in DB::ContextShared::~ContextShared() ()
#7  0x0000000002cb53c6 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#8  0x0000000002cb2331 in ?? ()
#9  0x0000000002cb2c71 in ?? ()
#10 0x0000000002c1b056 in DB::Server::main(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#11 0x0000000008501035 in Poco::Util::Application::run() ()
#12 0x0000000002cb2da8 in mainEntryClickHouseServer(int, char**) ()
#13 0x0000000002c1682f in main ()
```

**Comment by ztlpn** [comment]
Confirmed. It is a deadlock during the shutdown of Kafka tables if they didn't have a chance to start up.

**Comment by ztlpn** [comment]
fixed in master
