### ISSUE TITLE
ZooKeeperExceptions are not exceptions anymore

### ISSUE THREAD

**Issue by SaltTan** [yandex/ClickHouse#2316]
We get network issues quite often in our environment, so I set up an alert which fires when ZooKeeperExceptions in system.events increases. After upgrading to 1.1.54380 it increases by a few hundred every 5 minutes.
The only messages about ZooKeeper in logs are these:
```
<Debug> db.table (StorageReplicatedMergeTree): Removing 1 old parts from ZooKeeper
<Debug> db.table (StorageReplicatedMergeTree): Removed 1 old parts from ZooKeeper. Removing them from filesystem.
```
It seems that the behaviour was changed in 1.1.54371.
Is this a bug or a feature?

**Comment by alexey-milovidov** [comment]
The issue is clearly visible on graphs (from the random server):
![zk_exceptions](https://user-images.githubusercontent.com/18581488/44373482-19ff4200-a4f2-11e8-8275-b59b67c7c126.png)

Looks like it is better after upgrade to the latest revision.

**Comment by alexey-milovidov** [comment]
But the issue still exists. There are more exceptions on the graph that in logs.

**Comment by alexey-milovidov** [comment]
It is normal.

It happens in two locations:

```
#0  ZooKeeperImpl::Exception::Exception (this=0x452b9f280, msg=..., code=-110) at ../dbms/src/Common/ZooKeeper/ZooKeeperImpl.cpp:274
#1  0x0000000005443423 in zkutil::KeeperMultiException::KeeperMultiException (this=0x452b9f280, code=-110, requests=..., responses=...) at ../dbms/src/Common/ZooKeeper/ZooKeeper.cpp:837
#2  0x0000000005443a28 in zkutil::KeeperMultiException::check (code=-110, requests=..., responses=...) at ../dbms/src/Common/ZooKeeper/ZooKeeper.cpp:854
#3  0x0000000005443aaf in zkutil::ZooKeeper::multi (this=<optimized out>, requests=...) at ../dbms/src/Common/ZooKeeper/ZooKeeper.cpp:489
#4  0x000000000501f893 in DB::EphemeralLockInZooKeeper::EphemeralLockInZooKeeper (this=0x7f1747261e80, path_prefix_=..., temp_path=..., zookeeper_=..., precheck_ops=0x7f1747261d30)
    at ../dbms/src/Storages/MergeTree/EphemeralLockInZooKeeper.cpp:29
#5  0x0000000004fd79bf in DB::StorageReplicatedMergeTree::allocateBlockNumber (this=0x14d09610, partition_id=..., zookeeper=..., zookeeper_block_id_path=...) at ../dbms/src/Storages/StorageReplicatedMergeTree.cpp:3453
#6  0x00000000050b8cc9 in DB::ReplicatedMergeTreeBlockOutputStream::commitPart (this=this@entry=0x1ae763670, zookeeper=..., part=..., block_id=...) at ../dbms/src/Storages/MergeTree/ReplicatedMergeTreeBlockOutputStream.cpp:214
#7  0x00000000050bc08a in DB::ReplicatedMergeTreeBlockOutputStream::write (this=0x1ae763670, block=...) at ../dbms/src/Storages/MergeTree/ReplicatedMergeTreeBlockOutputStream.cpp:160
#8  0x0000000005200e13 in DB::PushingToViewsBlockOutputStream::write (this=0x60cb4ca40, block=...) at ../dbms/src/DataStreams/PushingToViewsBlockOutputStream.cpp:62
#9  0x0000000005185098 in DB::AddingDefaultBlockOutputStream::write (this=0x18af00790, block=...) at ../dbms/src/DataStreams/AddingDefaultBlockOutputStream.cpp:73
#10 0x0000000005206168 in DB::SquashingBlockOutputStream::finalize (this=this@entry=0x910fe3350) at ../dbms/src/DataStreams/SquashingBlockOutputStream.cpp:30
#11 0x00000000052063f1 in DB::SquashingBlockOutputStream::writeSuffix (this=0x910fe3350) at ../dbms/src/DataStreams/SquashingBlockOutputStream.cpp:50
#12 0x0000000002dba482 in DB::TCPHandler::processInsertQuery (this=this@entry=0x401bc6000, global_settings=...) at ../dbms/programs/server/TCPHandler.cpp:309
#13 0x0000000002dba9d7 in DB::TCPHandler::runImpl (this=this@entry=0x401bc6000) at ../dbms/programs/server/TCPHandler.cpp:163
#14 0x0000000002dbb7db in DB::TCPHandler::run (this=0x401bc6000) at ../dbms/programs/server/TCPHandler.cpp:791
#15 0x00000000058b355f in Poco::Net::TCPServerConnection::start (this=<optimized out>) at ../contrib/poco/Net/src/TCPServerConnection.cpp:43
#16 0x00000000058b393a in Poco::Net::TCPServerDispatcher::run (this=0xf342d00) at ../contrib/poco/Net/src/TCPServerDispatcher.cpp:114
#17 0x00000000059556d7 in Poco::PooledThread::run (this=0x29c747c00) at ../contrib/poco/Foundation/src/ThreadPool.cpp:214
#18 0x0000000005951598 in Poco::ThreadImpl::runnableEntry (pThread=<optimized out>) at ../contrib/poco/Foundation/src/Thread_STD.cpp:139
#19 0x000000000934596f in execute_native_thread_routine ()
#20 0x00007f1924488182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#21 0x00007f1923cab47d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
- when duplicate block is inserted, it is silently deduplicated.

```
#0  ZooKeeperImpl::Exception::Exception (this=0x26a211c80, msg=..., code=-110) at ../dbms/src/Common/ZooKeeper/ZooKeeperImpl.cpp:274
#1  0x0000000005443423 in zkutil::KeeperMultiException::KeeperMultiException (this=0x26a211c80, code=-110, requests=..., responses=...) at ../dbms/src/Common/ZooKeeper/ZooKeeper.cpp:837
#2  0x0000000005443a28 in zkutil::KeeperMultiException::check (code=-110, requests=..., responses=...) at ../dbms/src/Common/ZooKeeper/ZooKeeper.cpp:854
#3  0x0000000005443aaf in zkutil::ZooKeeper::multi (this=<optimized out>, requests=...) at ../dbms/src/Common/ZooKeeper/ZooKeeper.cpp:489
#4  0x0000000004fdf494 in DB::StorageReplicatedMergeTree::checkPartChecksumsAndCommit (this=this@entry=0x14d08410, transaction=..., part=...) at ../dbms/src/Storages/StorageReplicatedMergeTree.cpp:1016
#5  0x0000000004fe077e in DB::StorageReplicatedMergeTree::tryExecuteMerge (this=this@entry=0x14d08410, entry=...) at ../dbms/src/Storages/StorageReplicatedMergeTree.cpp:1273
#6  0x0000000004fe53fb in DB::StorageReplicatedMergeTree::executeLogEntry (this=0x14d08410, entry=...) at ../dbms/src/Storages/StorageReplicatedMergeTree.cpp:1100
#7  0x0000000004fe5aef in DB::StorageReplicatedMergeTree::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const (__closure=0x7f191fb6bc50, entry=...)
    at ../dbms/src/Storages/StorageReplicatedMergeTree.cpp:2131
#8  0x00000000050d6fd5 in operator() (__args#0=..., this=0x7f191fb6bc50) at /usr/include/c++/7/bits/std_function.h:706
#9  DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) (
    this=this@entry=0x14d08d70, get_zookeeper=..., entry=..., func=...) at ../dbms/src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp:1015
#10 0x0000000004fc16c0 in DB::StorageReplicatedMergeTree::queueTask (this=0x14d08410) at ../dbms/src/Storages/StorageReplicatedMergeTree.cpp:2164
#11 0x00000000050142de in operator() (this=<optimized out>) at /usr/include/c++/7/bits/std_function.h:706
#12 DB::BackgroundProcessingPool::threadFunction (this=0xf35bc90) at ../dbms/src/Storages/MergeTree/BackgroundProcessingPool.cpp:178
#13 0x000000000934596f in execute_native_thread_routine ()
#14 0x00007f1924488182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#15 0x00007f1923cab47d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
- when two or more replicas finish a merge simultaneously, they will try to add data part simultaneously - exception is thrown in something like compare-and-swap loop that will proceed to the next iteration.

The message
```
The part ... on a replica suddenly appeared, will recheck checksums
```
is output in log, and it is totally Ok.

**Comment by alexey-milovidov** [comment]
3b39f6a4c36512aeb49b36d2d8d962698e8419de will help.
