### ISSUE TITLE
FORMAT JSON doesn't seem to work

### ISSUE THREAD

**Issue by Joozty** [yandex/ClickHouse#2334]
I am trying to fetch some data in JSON format.

Here is simple query:
```sql
SELECT db.sample FROM db FORMAT JSON;
```

I am getting this error:
```java
[2018-05-09 13:08:30] [62] ClickHouse exception, code: 62, host: localhost, port: 8123; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 33: JSON FORMAT TabSeparatedWithNamesAndTypes;. Expected identifier, e.what() = DB::Exception
[2018-05-09 13:08:30] java.lang.Throwable: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 33: JSON FORMAT TabSeparatedWithNamesAndTypes;. Expected identifier, e.what() = DB::Exception
[2018-05-09 13:08:30] 	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
[2018-05-09 13:08:30] 	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
[2018-05-09 13:08:30] 	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:680)
[2018-05-09 13:08:30] 	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:512)
[2018-05-09 13:08:30] 	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:105)
[2018-05-09 13:08:30] 	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:89)
[2018-05-09 13:08:30] 	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:85)
[2018-05-09 13:08:30] 	at com.intellij.database.remote.jdbc.impl.RemoteStatementImpl.executeQuery(RemoteStatementImpl.java:161)
[2018-05-09 13:08:30] 	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
[2018-05-09 13:08:30] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2018-05-09 13:08:30] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2018-05-09 13:08:30] 	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
[2018-05-09 13:08:30] 	at sun.rmi.transport.Transport$1.run(Transport.java:200)
[2018-05-09 13:08:30] 	at sun.rmi.transport.Transport$1.run(Transport.java:197)
[2018-05-09 13:08:30] 	at java.security.AccessController.doPrivileged(Native Method)
[2018-05-09 13:08:30] 	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
[2018-05-09 13:08:30] 	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
[2018-05-09 13:08:30] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
[2018-05-09 13:08:30] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
[2018-05-09 13:08:30] 	at java.security.AccessController.doPrivileged(Native Method)
[2018-05-09 13:08:30] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
[2018-05-09 13:08:30] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2018-05-09 13:08:30] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2018-05-09 13:08:30] 	at java.lang.Thread.run(Thread.java:745) (no stack trace)
```

Without `FORMAT JSON ` it works fine but I need JSON support.

**Comment by filimonov** [comment]
When using clickhouse jdbc client you can't change the format of data interchange between client and server (otherwise jdbc client will not be able to parse out columns with data).

**Comment by Joozty** [comment]
@filimonov Thanks for quick answer.

**Comment by HadoopChen** [comment]
## SQL 
select * from tag limit 1 ;
## ERROR
Error running query: Code: 62, e.displayText() = DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 187 (end of query): ; FORMAT JSON. , e.what() = DB::Exception
## Beg For Help !

**Comment by filimonov** [comment]
> Multi-statements are not allowed

Remove semicolon from the query end. ;)

**Comment by 10wpressure** [comment]
@filimonov i spent embarassing amount of hours to find your post. Thank you!

**Comment by czarnapolana** [comment]
Hi Everyone !

I have a question to you.

I get an error message after puting a SQL query to Clickhouse DB but with the same account I can execute it from CLI level without errors. 

select * from Clickhouse_Store.Test_Backup1 INTO OUTFILE '/tmp/jsonExportFile.txt' FORMAT JSONEachRow

![clickhouse error](https://github.com/ClickHouse/ClickHouse/assets/26519435/7bca99d7-ca39-4f72-b6e3-2f7900b92011)

and from CLI is working fine:

![clickhouse error_from_CLI_OK](https://github.com/ClickHouse/ClickHouse/assets/26519435/c41e2bf1-4deb-49e5-9f01-06d8eadb2105)

If someone will now the answer or hint please help and thanks in advance !
KR
