### ISSUE TITLE
Merge Tree Crushing with Too many parts (1025) Exception

### ISSUE THREAD

**Issue by manojrbj** [yandex/ClickHouse#2811]
Hi Team,

I have 5 node clickhouse cluster with default settings. I am trying to ingest 4 TB of uncompressed (1.3TB of compressed: gZip) data with Spark Job. I have below configuration of Spark job. 
`driver-memory 5g num-executors 14 executor-memory 10g executor-cores 5`

I am creating batch of 25000 and ingesting through executeBatch() method into clickhouse. While executing the job, It lands into **Too many parts (1025) Exception**
Below is detailed exception.
```
Job aborted due to stage failure: Task 9 in stage 0.0 failed 4 times, most recent failure: Lost task 9.3 in stage 0.0 (TID 145, cdh09, executor 14): com.github.housepower.jdbc.ClickHouseSQLException: DB::ExceptionDB::Exception: Too many parts (1025). Merges are processing significantly slower than inserts.. Stack trace:
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x48abed6]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2682dcf]
2. clickhouse-server(DB::MergeTreeData::delayInsertOrThrowIfNeeded(Poco::Event*) const+0x3a7) [0x431ccc7]
3. clickhouse-server(DB::MergeTreeBlockOutputStream::write(DB::Block const&)+0x2c) [0x4314cfc]
4. clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x31) [0x44b38a1]
5. clickhouse-server(DB::AddingDefaultBlockOutputStream::write(DB::Block const&)+0x9a1) [0x44442c1]
6. clickhouse-server(DB::SquashingBlockOutputStream::finalize()+0x1ef) [0x44b8b6f]
7. clickhouse-server(DB::SquashingBlockOutputStream::writeSuffix()+0x11) [0x44b8e21]
8. clickhouse-server(DB::DistributedBlockOutputStream::writeToLocal(DB::Block const&, unsigned long)+0x80) [0x42f6090]
9. clickhouse-server(DB::DistributedBlockOutputStream::writeAsyncImpl(DB::Block const&, unsigned long)+0x22b) [0x42f99db]
10. clickhouse-server(DB::DistributedBlockOutputStream::writeSplitAsync(DB::Block const&)+0x7e) [0x42f9c1e]
11. clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x31) [0x44b38a1]
12. clickhouse-server(DB::AddingDefaultBlockOutputStream::write(DB::Block const&)+0x9a1) [0x44442c1]
13. clickhouse-server(DB::SquashingBlockOutputStream::finalize()+0x1ef) [0x44b8b6f]
14. clickhouse-server(DB::SquashingBlockOutputStream::writeSuffix()+0x11) [0x44b8e21]
15. clickhouse-server(DB::TCPHandler::processInsertQuery(DB::Settings const&)+0x292) [0x268cd42]
16. clickhouse-server(DB::TCPHandler::runImpl()+0x43c) [0x268d24c]
17. clickhouse-server(DB::TCPHandler::run()+0x1c) [0x268e0ac]
18. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x49eefaf]
19. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x110) [0x49ef610]
20. clickhouse-server(Poco::PooledThread::run()+0x77) [0x4a4df27]
21. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x4a4b488]
22. clickhouse-server() [0x4d3fe1f]
23. /lib64/libpthread.so.0(+0x7e25) [0x7f0f5f13ee25]
24. /lib64/libc.so.6(clone+0x6d) [0x7f0f5e962bad]
at com.github.housepower.jdbc.protocol.ExceptionResponse.readExceptionFrom(ExceptionResponse.java:32)
at com.github.housepower.jdbc.protocol.RequestOrResponse.readFrom(RequestOrResponse.java:38)
at com.github.housepower.jdbc.connect.PhysicalConnection.receiveResponse(PhysicalConnection.java:86)
at com.github.housepower.jdbc.connect.PhysicalConnection.receiveEndOfStream(PhysicalConnection.java:78)
at com.github.housepower.jdbc.ClickHouseConnection.sendInsertRequest(ClickHouseConnection.java:132)
at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.executeBatch(ClickHousePreparedInsertStatement.java:61)
at com.bistel.clickhouse.ingetion.LoadData$IngestMergeTreeDataFuntNative.call(LoadData.java:224)
at com.bistel.clickhouse.ingetion.LoadData$IngestMergeTreeDataFuntNative.call(LoadData.java:1)
at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
at org.apache.spark.scheduler.Task.run(Task.scala:89)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```
Any help is much appreciated.

Thanks.

**Comment by lamber-ken** [comment]
Hi, reduce the parallelism of sink which inserts datas into CK server.

**Comment by alexey-milovidov** [comment]
"Too many parts" error usually means that the replica fails to process merges. There may be two reasons:
1. merges are not processing at all due to misconfiguration, network issues or logical error.
2. merges are processing not fast enough due to high load.

First reason is more common.

To figure out the reason, you should look at:

`system.replicas` table
- check is_leader field, number of active replicas, queue size, number of merges in queue;

Note that only leader replica can assign merges. If it will not assign merges, all replicas cannot merge new inserted data.

Check number of active replicas to be sure that you don't have some replicas that you are not aware of.

If you have high number of merges in queue - it means that replica cannot do merges for some reason.

`system.replication_queue` table

Check all entries that are related to merges. Often you can see the reason, why merges cannot be processed in "exception" field.

If merges are processing, but not just fast enough (you see big number of merges in `system.merges` table and high load either on CPU or IO), you just have to lower ingestion rate.
