### ISSUE TITLE
ClickHouse exception, code: 164 connecting to clickhouse from jetbrain IDEA with jdbc driver

### ISSUE THREAD

**Issue by stiv-yakovenko** [yandex/ClickHouse#2820]
![image](https://user-images.githubusercontent.com/4163254/43785648-fbabf2c8-9a90-11e8-9170-2a00f3419355.png)

```
[2018-08-07 18:09:51] [164] ClickHouse exception, code: 164, host: XX.X.X.XX, port: 8123; Code: 164, e.displayText() = DB::Exception: Cannot override setting (result_overflow_mode) in readonly mode, e.what() = DB::Exception
[2018-08-07 18:09:51] java.lang.Throwable: Code: 164, e.displayText() = DB::Exception: Cannot override setting (result_overflow_mode) in readonly mode, e.what() = DB::Exception
[2018-08-07 18:09:51] 	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
[2018-08-07 18:09:51] 	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
[2018-08-07 18:09:51] 	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:680)
[2018-08-07 18:09:51] 	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:512)
[2018-08-07 18:09:51] 	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:105)
[2018-08-07 18:09:51] 	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:89)
[2018-08-07 18:09:51] 	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:85)
[2018-08-07 18:09:51] 	at com.intellij.database.remote.jdbc.impl.RemoteStatementImpl.executeQuery(RemoteStatementImpl.java:161)
[2018-08-07 18:09:51] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2018-08-07 18:09:51] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2018-08-07 18:09:51] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2018-08-07 18:09:51] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2018-08-07 18:09:51] 	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
[2018-08-07 18:09:51] 	at sun.rmi.transport.Transport$1.run(Transport.java:200)
[2018-08-07 18:09:51] 	at sun.rmi.transport.Transport$1.run(Transport.java:197)
[2018-08-07 18:09:51] 	at java.security.AccessController.doPrivileged(Native Method)
[2018-08-07 18:09:51] 	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
[2018-08-07 18:09:51] 	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
[2018-08-07 18:09:51] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
[2018-08-07 18:09:51] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
[2018-08-07 18:09:51] 	at java.security.AccessController.doPrivileged(Native Method)
[2018-08-07 18:09:51] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
[2018-08-07 18:09:51] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2018-08-07 18:09:51] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2018-08-07 18:09:51] 	at java.lang.Thread.run(Thread.java:745) (no stack trace)
```

I have readonly access to the database. How can I address this problem?

**Comment by blinkov** [comment]
You need to set the readonly setting of this user to value 2. Such user still won't be able to change data in tables, but clients which try to silently override settings will start working.

See https://clickhouse.yandex/docs/en/operations/settings/query_complexity/#readonly

**Comment by stiv-yakovenko** [comment]
thank you this helps

**Comment by winter7** [comment]
why does `select 1` cause this exception?

**Comment by den-crane** [comment]
Because a client tries to change the parameter `set result_overflow_mode='break` to limit rows returned by a query. And it needs READ_ONLY mode =2
