### ISSUE TITLE
RuntimeError: ERROR: Link [словаря](../../query_language/dicts/external_dicts.md) in file operations/table_engines/dictionary.md has no anchor

### ISSUE THREAD

**Issue by denisgolius** [yandex/ClickHouse#3347]
I want to host Clickhouse docs mirror on my server, so I register clickhouse.xyz, but building documentation ended with error... please fix this issue. 

```
/home/docs/www/ClickHouse/docs/tools # python build.py 
INFO:root:Building en docs
INFO:mkdocs.commands.build:Cleaning site directory
INFO:mkdocs.commands.build:Building documentation to directory: /home/docs/www/ClickHouse/docs/build/en
INFO:root:Building single page version for en
INFO:root:146 files will be concatenated into single md-file.
INFO:root:Building ru docs
INFO:mkdocs.structure.nav:The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - query_language/table_functions/jdbc.md
INFO:root:Building single page version for ru
INFO:root:146 files will be concatenated into single md-file.
Traceback (most recent call last):
  File "build.py", line 199, in <module>
    build(args)
  File "/home/docs/www/ClickHouse/docs/tools/build.py", line 174, in build
    build_for_lang(lang, args)
  File "/home/docs/www/ClickHouse/docs/tools/build.py", line 112, in build_for_lang
    build_single_page_version(lang, args, cfg)
  File "/home/docs/www/ClickHouse/docs/tools/build.py", line 154, in build_single_page_version
    single_page_output_path
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/docs/www/ClickHouse/docs/tools/build.py", line 33, in autoremoved_file
    yield handle
  File "/home/docs/www/ClickHouse/docs/tools/build.py", line 122, in build_single_page_version
    concatenate(lang, args.docs_dir, single_md)
  File "/home/docs/www/ClickHouse/docs/tools/concatenate.py", line 61, in concatenate
    l = re.sub(r'\[.+?\]\(.+?\)', link_proc, l)
  File "/home/docs/www/ClickHouse/docs/tools/venv/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/docs/www/ClickHouse/docs/tools/concatenate.py", line 57, in link_proc
    path + ' has no anchor. Please provide it.')
RuntimeError: ERROR: Link [словаря](../../query_language/dicts/external_dicts.md) in file operations/table_engines/dictionary.md has no anchor. Please provide it.

```

**Comment by blinkov** [comment]
#3354
