### ISSUE TITLE
 hive date input Clickhouse by  kettle   using  MergetTree  engine error

### ISSUE THREAD

**Issue by wangpengpeng** [yandex/ClickHouse#3538]
**Date**   must be Requirements   By mergeTree engine ,But report error
error code follow:

2018/11/05 13:52:57 - Carte - Installing timer to purge stale objects after 1440 minutes.
2018/11/05 13:54:08 - Spoon - Using legacy execution engine
2018/11/05 13:54:08 - Spoon - 转换已经打开.
2018/11/05 13:54:08 - Spoon - 正在打开转换 [test_hive2clickhouse]...
2018/11/05 13:54:08 - Spoon - 开始执行转换.
2018/11/05 13:54:08 - test_hive2clickhouse - 为了转换解除补丁开始  [test_hive2clickhouse]
2018/11/05 13:54:09 - clickhouse.0 - Connected to database [test_ch] (commit=1000)
2018/11/05 13:54:09 - clickhouse.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Because of an error, this step can't continue:
2018/11/05 13:54:09 - clickhouse.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2018/11/05 13:54:09 - clickhouse.0 - Error inserting row into table [mark_activity_send_log] with values: [81947000], [18917125050], [2018-10-10]
2018/11/05 13:54:09 - clickhouse.0 - 
2018/11/05 13:54:09 - clickhouse.0 - offending row : [act_send_id Integer(15)], [target String(500)], [create_date String(2147483647)]
2018/11/05 13:54:09 - clickhouse.0 - 
2018/11/05 13:54:09 - clickhouse.0 - Error setting value #3 [String(2147483647)] on prepared statement
2018/11/05 13:54:09 - clickhouse.0 -  at java.lang.Thread.run (Thread.java:748)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.trans.step.RunThread.run (RunThread.java:62)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.trans.steps.tableoutput.TableOutput.processRow (TableOutput.java:125)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.trans.steps.tableoutput.TableOutput.writeToTable (TableOutput.java:261)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.core.database.Database.setValues (Database.java:1076)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.core.database.Database.setValue (Database.java:1060)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.core.row.value.ValueMetaBase.setPreparedStatementValue (ValueMetaBase.java:5042)
2018/11/05 13:54:09 - clickhouse.0 -  at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.setCharacterStream (ClickHousePreparedStatementImpl.java:427)
2018/11/05 13:54:09 - clickhouse.0 - 
2018/11/05 13:54:09 - clickhouse.0 - 
2018/11/05 13:54:09 - clickhouse.0 - 
2018/11/05 13:54:09 - clickhouse.0 - 	at org.pentaho.di.trans.steps.tableoutput.TableOutput.writeToTable(TableOutput.java:385)
2018/11/05 13:54:09 - clickhouse.0 - 	at org.pentaho.di.trans.steps.tableoutput.TableOutput.processRow(TableOutput.java:125)
2018/11/05 13:54:09 - clickhouse.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2018/11/05 13:54:09 - clickhouse.0 - 	at java.lang.Thread.run(Thread.java:748)
2018/11/05 13:54:09 - clickhouse.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2018/11/05 13:54:09 - clickhouse.0 - offending row : [act_send_id Integer(15)], [target String(500)], [create_date String(2147483647)]
2018/11/05 13:54:09 - clickhouse.0 - 
2018/11/05 13:54:09 - clickhouse.0 - Error setting value #3 [String(2147483647)] on prepared statement
2018/11/05 13:54:09 - clickhouse.0 -  at java.lang.Thread.run (Thread.java:748)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.trans.step.RunThread.run (RunThread.java:62)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.trans.steps.tableoutput.TableOutput.processRow (TableOutput.java:125)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.trans.steps.tableoutput.TableOutput.writeToTable (TableOutput.java:261)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.core.database.Database.setValues (Database.java:1076)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.core.database.Database.setValue (Database.java:1060)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.core.row.value.ValueMetaBase.setPreparedStatementValue (ValueMetaBase.java:5042)
2018/11/05 13:54:09 - clickhouse.0 -  at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.setCharacterStream (ClickHousePreparedStatementImpl.java:427)
2018/11/05 13:54:09 - clickhouse.0 - 
2018/11/05 13:54:09 - clickhouse.0 - 
2018/11/05 13:54:09 - clickhouse.0 - 	at org.pentaho.di.core.database.Database.setValues(Database.java:1078)
2018/11/05 13:54:09 - clickhouse.0 - 	at org.pentaho.di.trans.steps.tableoutput.TableOutput.writeToTable(TableOutput.java:261)
2018/11/05 13:54:09 - clickhouse.0 - 	... 3 more
2018/11/05 13:54:09 - clickhouse.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2018/11/05 13:54:09 - clickhouse.0 - Error setting value #3 [String(2147483647)] on prepared statement
2018/11/05 13:54:09 - clickhouse.0 -  at java.lang.Thread.run (Thread.java:748)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.trans.step.RunThread.run (RunThread.java:62)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.trans.steps.tableoutput.TableOutput.processRow (TableOutput.java:125)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.trans.steps.tableoutput.TableOutput.writeToTable (TableOutput.java:261)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.core.database.Database.setValues (Database.java:1076)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.core.database.Database.setValue (Database.java:1060)
2018/11/05 13:54:09 - clickhouse.0 -  at org.pentaho.di.core.row.value.ValueMetaBase.setPreparedStatementValue (ValueMetaBase.java:5042)
2018/11/05 13:54:09 - clickhouse.0 -  at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.setCharacterStream (ClickHousePreparedStatementImpl.java:427)
2018/11/05 13:54:09 - clickhouse.0 - 
2018/11/05 13:54:09 - clickhouse.0 - 	at org.pentaho.di.core.row.value.ValueMetaBase.setPreparedStatementValue(ValueMetaBase.java:5128)
2018/11/05 13:54:09 - clickhouse.0 - 	at org.pentaho.di.core.database.Database.setValue(Database.java:1060)
2018/11/05 13:54:09 - clickhouse.0 - 	at org.pentaho.di.core.database.Database.setValues(Database.java:1076)
2018/11/05 13:54:09 - clickhouse.0 - 	... 4 more
2018/11/05 13:54:09 - clickhouse.0 - Caused by: java.sql.SQLFeatureNotSupportedException
2018/11/05 13:54:09 - clickhouse.0 - 	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.setCharacterStream(ClickHousePreparedStatementImpl.java:427)
2018/11/05 13:54:09 - clickhouse.0 - 	at org.pentaho.di.core.row.value.ValueMetaBase.setPreparedStatementValue(ValueMetaBase.java:5042)
2018/11/05 13:54:09 - clickhouse.0 - 	... 6 more
2018/11/05 13:54:09 - hive.0 - Finished reading query, closing connection.
2018/11/05 13:54:09 - clickhouse.0 - 完成处理 (I=0, O=0, R=1, W=0, U=0, E=1)
2018/11/05 13:54:09 - test_hive2clickhouse - 转换被检测
2018/11/05 13:54:09 - test_hive2clickhouse - 转换正在杀死其他步骤!
2018/11/05 13:54:09 - hive.0 - 完成处理 (I=10, O=0, R=0, W=10, U=0, E=0)
2018/11/05 13:54:09 - test_hive2clickhouse - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : 错误被检测到!
2018/11/05 13:54:09 - Spoon - 转换完成!!
2018/11/05 13:54:09 - test_hive2clickhouse - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : 错误被检测到!
2018/11/05 13:54:09 - test_hive2clickhouse - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : 错误被检测到!

**Comment by den-crane** [comment]
So the error is in jdbc driver not in CH https://github.com/yandex/clickhouse-jdbc

 java.sql.SQLFeatureNotSupportedException
 ru.yandex.clickhouse.ClickHousePreparedStatementImpl.setCharacterStream(ClickHousePreparedStatementImpl.java:427

**Comment by leow3811** [comment]
Hello, buddy, I want to use kettle to store data from mysql to  CK , Can you tell me how to do ?

**Comment by leow3811** [comment]
i have dealt with this problem ,thanks anyway

**Comment by Morpheus1999** [comment]
> 

Hi dude May I ask how did you deal with it？I face same issue from postgres to CH via kettle.

**Comment by Morpheus1999** [comment]
> i have dealt with this problem ,thanks anyway
Hi dude May I ask how did you deal with it？I face same issue from postgres to CH via kettle.

**Comment by lampjian** [comment]
This kettle clickhouse plugin bug can be fixed by using a field-selection widget. Here is the solution: https://blog.csdn.net/qq_43247999/article/details/118669818
