### ISSUE TITLE
ClickHouse-jdbc Broken pipe

### ISSUE THREAD

**Issue by lamber-ken** [yandex/ClickHouse#6503]
Hi, all.
I use spark write data to clickhouse by clickhouse-jdbc:0.1.54, but met some errors accidentally. 

Does this have anything to do with the configuration item `listen_backlog`?

How to solve this problem? thanks very match !

#### Env
clickhouse-jdbc: 0.1.54
clickhouse: 19.11.5.28

```
<max_connections>4096</max_connections>
<keep_alive_timeout>10</keep_alive_timeout>

<!-- Maximum number of concurrent queries. -->
<max_concurrent_queries>200</max_concurrent_queries>

<max_open_files>1000000</max_open_files>
```

#### Detail stackstrace 
```
[INFO 2019-08-15 11:19:12 (org.apache.http.impl.execchain.RetryExec:96)] I/O exception (java.net.SocketException) caught when processing request to {}->http://xx.xx.xx.xx:17133: Broken pipe
```
```
[ERROR 2019-08-15 11:19:12 (com.ly.data.ysck.tool.CKTool:47)] 插入异常
ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 172.20.89.26, port: 17133; Broken pipe
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:88)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:24)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:795)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:773)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:363)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:348)
	at com.ly.data.ysck.tool.CKTool.inseartData(CKTool.java:84)
	at com.ly.data.ysck.tool.CKTool.inseartAction(CKTool.java:44)
	at com.ly.data.ysck.app.SparkDemo$1.call(SparkDemo.java:84)
	at com.ly.data.ysck.app.SparkDemo$1.call(SparkDemo.java:33)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartition$1.apply(JavaRDDLike.scala:219)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartition$1.apply(JavaRDDLike.scala:219)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:925)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:925)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:126)
	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:138)
	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:160)
	at org.apache.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:124)
	at org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:181)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at com.google.common.io.LittleEndianDataOutputStream.write(LittleEndianDataOutputStream.java:57)
	at ru.yandex.clickhouse.util.ClickHouseLZ4OutputStream.writeBlock(ClickHouseLZ4OutputStream.java:53)
	at ru.yandex.clickhouse.util.ClickHouseLZ4OutputStream.write(ClickHouseLZ4OutputStream.java:33)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.OutputStream.write(OutputStream.java:75)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl$BatchHttpEntity.writeTo(ClickHousePreparedStatementImpl.java:395)
	at ru.yandex.clickhouse.BodyEntityWrapper.writeTo(BodyEntityWrapper.java:43)
	at ru.yandex.clickhouse.LZ4EntityWrapper.writeTo(LZ4EntityWrapper.java:43)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:789)
	... 19 more
```

**Comment by den-crane** [comment]
Check errors in CH server log. It could a network issue.

**Comment by lamber-ken** [comment]
> Check errors in CH server log. It could a network issue.

Hi, the network should not have problems, because I found a regular that when I reduce the parallelism of writing threads, this problem does not occur.

**Comment by den-crane** [comment]
So you've suspect an issue in clickhouse-jdbc then? 
Check CH logs for errors.

**Comment by lamber-ken** [comment]
> So you've suspect an issue in clickhouse-jdbc then?
> Check CH logs for errors.

I think may modify some configuration item will solve this problem.

btw, I checked the `clickhouse-server.err.log` just now, no error logs.

**Comment by den-crane** [comment]
Try to set in JDBC!!! socket_timeout = 300000

**Comment by lamber-ken** [comment]
> Try to set in JDBC!!! socket_timeout = 300000

Thanks for your solution, it works 👍

**Comment by gubinjie** [comment]
@lamber-ken 
http_send_timeout and http_receive_timeout. Are these two parameters configured in config.xml or users.xml? The unit of the parameter is seconds?

**Comment by wangweiA** [comment]
@gubinjie
Add these two configuration parameters in  the file  "/etc/clickhouse-server/users.xml"  and restart clickhouse-server :
    <http_send_timeout>3600</http_send_timeout>
    <http_receive_timeout>3600</http_receive_timeout>
the unit is Seconds.

**Comment by gubinjie** [comment]
@wangweiA Thank you, it has been solved long ago. It is better to use socket_timeout. This configuration item contains http_send_timeout and http_receive_timeout.
